### ISSUE TITLE
First Meeting for Task 1?

### ISSUE THREAD

**Issue by thuanGIT** [data301-2020-winter2/course-project-group_1039#1]
Hey @RitaLam,

Should we schedule a meeting to work on task 1? I think we are still missing Leo but we can start planning now.

I guess Task 1 is just **choosing a data set** and explaining **why we use it** and **which information from the data to extract**.

So, shall we have a zoom call this week?

**Comment by RitaLam** [comment]
Yess of course. How is your guys availability? I am very free on Wednesday and Thursday, and also can do weekend.
Please let me know I can send out the zoom invite as well

**Comment by thuanGIT** [comment]
I can do Thursday all day except (3PM-4PM PST) and weekends are all good!

**Comment by RitaLam** [comment]
> I can do Thursday all day except (3PM-4PM PST) and weekends are all good!
Sweet. Can we do Thursday 5pm?  Let see if Leo will accept this assignment, I will send him a direct message on canvas first.

**Comment by thuanGIT** [comment]
That sounds good! I will wait for the zoom link! (maybe we send on canvas?)

**Comment by RitaLam** [comment]
Heyy I sent the zoom invite on canvas in our group as an anoucement (idk how we direct message him??)
Let me know if you can see it or not :)

**Comment by thuanGIT** [comment]
Heyy I saw it! Not sure about if Leo saw it :)) But lets wait till tonight!

**Comment by thuanGIT** [comment]
Meeting 1 is done! Just 1 hour late!
