### ISSUE TITLE
Meeting 2

### ISSUE THREAD

**Issue by RitaLam** [data301-2020-winter2/course-project-group_1039#11]
Hi Jamie and Leo, 
 Could we please all meet on Thursday 5pm? I have heard back from the TA let's finalize our tasks before submission.
Please use the following link:

Rita Lam is inviting you to a scheduled Zoom meeting.

Topic: Rita Lam's Personal Meeting Room

Join Zoom Meeting
https://us04web.zoom.us/j/7910254325?pwd=WlRLN3FPUGc4N0UwRTdLUjNvTmlsQT09

Meeting ID: 791 025 4325
Passcode: 1Uchei

See you guys there!

**Comment by thuanGIT** [comment]
Let's vote who is coming!

[![](https://api.gh-polls.com/poll/01EY7E91KKZ8DXGVMXRCZS67MC/Going)](https://api.gh-polls.com/poll/01EY7E91KKZ8DXGVMXRCZS67MC/Going/vote)
[![](https://api.gh-polls.com/poll/01EY7E91KKZ8DXGVMXRCZS67MC/Nah%20I%20am%20busy)](https://api.gh-polls.com/poll/01EY7E91KKZ8DXGVMXRCZS67MC/Nah%20I%20am%20busy/vote)
