### ISSUE TITLE
Tasks for Feb 4-Feb 10

### ISSUE THREAD

**Issue by thuanGIT** [data301-2020-winter2/course-project-group_1039#2]
Hi everyone,

Here are the tasks for you! Please complete in the time assigned. If you need help, please let the team know.

@RitaLam 

- [x] Create a list of selected datasets.
- [x] Pick one dataset.
- [x] Learn Git branch
- [x] Edit README.md with your name and info.
- [x] Load csv file in a Jupiter notebook Task 4.
- [x] Send dataset to Haneen for acceptance

@Leo

- [x] Accept the repo to group project.
- [x] Pick a choice of the selected datasets.
- [x] Edit README.md with your name and info.
- [x] Learn Git Branch (skip u know it ^^)
- [x] Befriend on social media to contact.

@thuanGIT 

- [x] Complete the repo structure in Part 1.
- [x] Pick one dataset.
- [x] Download and push the dataset to the repo Task 3.
- [x] Load it in a Jupiter notebook Task 4.
- [x] Create a poll on data sets
- [x] Edit README.md with your name and info.

**Comment by thuanGIT** [comment]
Please use the poll below to vote for which data set you like. If you want to add more, please comment below!

[![](https://api.gh-polls.com/poll/01EXRN417WVCYZR2JSKJ29CB3W/1.%20%5BBig%20Five%20personality%20test%5D(https%3A%2F%2Fwww.kaggle.com%2Ftunguz%2Fbig-five-personality-test%3FfileType%3Dcsv%26sizeStart%3D100%252CMB%26sizeEnd%3D500%252CMB))](https://api.gh-polls.com/poll/01EXRN417WVCYZR2JSKJ29CB3W/1.%20%5BBig%20Five%20personality%20test%5D(https%3A%2F%2Fwww.kaggle.com%2Ftunguz%2Fbig-five-personality-test%3FfileType%3Dcsv%26sizeStart%3D100%252CMB%26sizeEnd%3D500%252CMB)/vote)
[![](https://api.gh-polls.com/poll/01EXRN417WVCYZR2JSKJ29CB3W/2.%5BUS%20baby%20names%5D(https%3A%2F%2Fwww.kaggle.com%2Fkaggle%2Fus-baby-names%3Fselect%3DNationalReadMe.pdf%26fbclid%3DIwAR0vB2lviB1XUwEUJcvxXCsmic5WWJPrFjVsKpg7H0Jwh33ypOdViAa1-PA))](https://api.gh-polls.com/poll/01EXRN417WVCYZR2JSKJ29CB3W/2.%5BUS%20baby%20names%5D(https%3A%2F%2Fwww.kaggle.com%2Fkaggle%2Fus-baby-names%3Fselect%3DNationalReadMe.pdf%26fbclid%3DIwAR0vB2lviB1XUwEUJcvxXCsmic5WWJPrFjVsKpg7H0Jwh33ypOdViAa1-PA)/vote)
[![](https://api.gh-polls.com/poll/01EXRN417WVCYZR2JSKJ29CB3W/3.%20%5BMars%20weather%5D(https%3A%2F%2Fgithub.com%2Fthe-pudding%2Fdata%2Ftree%2Fmaster%2Fmars-weather))](https://api.gh-polls.com/poll/01EXRN417WVCYZR2JSKJ29CB3W/3.%20%5BMars%20weather%5D(https%3A%2F%2Fgithub.com%2Fthe-pudding%2Fdata%2Ftree%2Fmaster%2Fmars-weather)/vote)
[![](https://api.gh-polls.com/poll/01EXRN417WVCYZR2JSKJ29CB3W/4.%20%5BAmazon%20Unlocked%20Phone%20Reviews%5D(https%3A%2F%2Fwww.kaggle.com%2FPromptCloudHQ%2Famazon-reviews-unlocked-mobile-phones))](https://api.gh-polls.com/poll/01EXRN417WVCYZR2JSKJ29CB3W/4.%20%5BAmazon%20Unlocked%20Phone%20Reviews%5D(https%3A%2F%2Fwww.kaggle.com%2FPromptCloudHQ%2Famazon-reviews-unlocked-mobile-phones)/vote)
[![](https://api.gh-polls.com/poll/01EXRN417WVCYZR2JSKJ29CB3W/5.%20%5BCrime%20in%20Chicago%5D(https%3A%2F%2Fwww.kaggle.com%2Fchicago%2Fchicago-crime))](https://api.gh-polls.com/poll/01EXRN417WVCYZR2JSKJ29CB3W/5.%20%5BCrime%20in%20Chicago%5D(https%3A%2F%2Fwww.kaggle.com%2Fchicago%2Fchicago-crime)/vote)

**Comment by thuanGIT** [comment]
**Reference link to data sets:**

| Name | Link|
|:----:|:----:|
|US Baby Name|[Here](https://www.kaggle.com/kaggle/us-baby-names)|
|Amazon Phone Reviews|[Here](https://www.kaggle.com/PromptCloudHQ/amazon-reviews-unlocked-mobile-phones)|
|Chicago Crime|[Here](https://www.kaggle.com/chicago/chicago-crime)|
|Big Five Personality Test|[Here](https://www.kaggle.com/tunguz/big-five-personality-test)|
|Mars Weather|[Here](https://github.com/the-pudding/data/tree/master/mars-weather)|

**Comment by thuanGIT** [comment]
**I think this website is a really good start to learn about Git Branch. Please click on the image!**

[![Untitled](https://user-images.githubusercontent.com/68053619/107079269-7333bc80-67a4-11eb-9d93-443c0e2f42d2.jpg)](https://www.atlassian.com/git/tutorials)

**Comment by thuanGIT** [comment]
@lhenon999 Could you vote on the poll on the data set?

**Comment by RitaLam** [comment]
Hello All,

It seems like we have a winner of the datasets: The Mars Weather!!
I will have the description of it done by tomorrow (Task 3 essay 1) and upload it on Github. You guys can all take a look let's set up a meeting on Thursday or Friday/ (weekend if you guys prefer) before the first deadline (I believe it's been delayed to the 17th now so no rushing).
Please comments below on your avilability and prefer meeting time, so we can all chat and finish the tasks.
I am most free on Thursday noon/ afternoon and Friday morning. 

Talk to you guys soon :)
Rita

**Comment by thuanGIT** [comment]
I am free on Thursday except 3PM-4PM and Saturdays! 

Btw, we have a few tasks left before Feb 10, so try your best to complete them everyone!

And make sure to ***mark your task done*** and ***update GitHub repo via pull requests***.  

Please **do not use 'main' or 'master' branch**. It would overwrite source codes and might introduce bugs.

**Comment by lhenon999** [comment]
Hello all, 

I am free on most days in the afternoon, thursday for friday anytime after 4pm works for me.

**Comment by RitaLam** [comment]
Let's meet on Thursday 5pm (Kelowna time pls, join using zoom link please).
