### ISSUE TITLE
Meeting 3 for MileStone 2

### ISSUE THREAD

**Issue by thuanGIT** [data301-2020-winter2/course-project-group_1039#22]
Hi everyone,

I think Milestone 2 is on so I guess we should meet up to divide the tasks. Let's agree on whether we want to meet this week or next week and decide on the time ^^

[![](https://api.gh-polls.com/poll/01EZ6ECVE5TSM03S6WSXKGZZ8M/This%20week%20)](https://api.gh-polls.com/poll/01EZ6ECVE5TSM03S6WSXKGZZ8M/This%20week%20/vote)
[![](https://api.gh-polls.com/poll/01EZ6ECVE5TSM03S6WSXKGZZ8M/Next%20week)](https://api.gh-polls.com/poll/01EZ6ECVE5TSM03S6WSXKGZZ8M/Next%20week/vote)

**Comment by RitaLam** [comment]
Hi guys!

Hope y'all had a fantastic reading break. Could we all meet this week or weekend for our Milestone 2 project? I saw there are quite a lot of stuff we have to go through so let's start early and we have more time to work on our own tasks.
I would prefer this Thursday or Friday at night as I am quite busy during the day. Let me know if 7 pm is too late for you guys or not; We can also have the meeting on the weekend if everybody is too busy during the week. Any preference on the time can be posted here or on discord. Talk to you guys soon :)

**Comment by thuanGIT** [comment]
Let's meet this week since next week is gonna be super busy! Here is the poll for every one to choose the slot.

[![](https://api.gh-polls.com/poll/01EZ71Y0XSFS35BM0KEZRP8R63/Thursday%20(7PM-8PM))](https://api.gh-polls.com/poll/01EZ71Y0XSFS35BM0KEZRP8R63/Thursday%20(7PM-8PM)/vote)
[![](https://api.gh-polls.com/poll/01EZ71Y0XSFS35BM0KEZRP8R63/Friday%20(7PM-8PM))](https://api.gh-polls.com/poll/01EZ71Y0XSFS35BM0KEZRP8R63/Friday%20(7PM-8PM)/vote)
[![](https://api.gh-polls.com/poll/01EZ71Y0XSFS35BM0KEZRP8R63/Weekends%20(Anytime%20but%20morning%20is%20better))](https://api.gh-polls.com/poll/01EZ71Y0XSFS35BM0KEZRP8R63/Weekends%20(Anytime%20but%20morning%20is%20better)/vote)
[![](https://api.gh-polls.com/poll/01EZ71Y0XSFS35BM0KEZRP8R63/No!%20Other%20time%20please!)](https://api.gh-polls.com/poll/01EZ71Y0XSFS35BM0KEZRP8R63/No!%20Other%20time%20please!/vote)

**Comment by thuanGIT** [comment]
Alright, it looks like we are meeting this Thursday! See y'all tmr!
