### ISSUE TITLE
Milestone 2 feedback 

### ISSUE THREAD

**Issue by Abu-Hijleh** [data301-2020-winter2/course-project-group_1039#49]
Overall, really good job! It was hard to find something to point out for you to fix. 

Must fix: 
- [x] In order to make the report more organized make sure all of task 5 is only found in the shared analysis ipynb, and that your individual files only contain EDA from task 4. You currently go into task 5 like analysis within your eda files.

**Comment by thuanGIT** [comment]
Thank you Haneen! We will work on it!
