### ISSUE TITLE
Some feedback/comments

### ISSUE THREAD

**Issue by KafkaNoNeko** [data301-2020-winter2/course-project-group_1039#54]
Hi!  

I'm mostly here to annoy @thuanGIT but your analysis is pretty interesting!

One area I think you could however improve on is the background research.  The comments explain the plots really well but perhaps adding some more comments on the results would make the analysis more interesting?

For example, why was 'Mary' such a popular name?  The name has roots in Christianity and also tends to be used as a middle name pretty often.  Are there states/regions which are known to be more religious historically and where names with religious connotations dominate?  The last graph shows that 'Mary' is not a common name anymore.  Why do you think so? (e.g. people becoming less religious etc)

For your second research question, I feel that analysing the trends for both genders separately would provide more insight.

**Comment by thuanGIT** [comment]
Haha thanks Paula! We will definitely go updating the work^^
